### ISSUE TITLE
Question: Doesn't work with ESLint

### ISSUE THREAD

**Issue by amilajack** [mrapogee/babel-plugin-transform-pipeline-operator#2]
This isnt an issue the this module (I believe). `babel-eslint` cannot correctly parse the syntax of this plugin:

<img width="527" alt="screen shot 2016-10-10 at 11 04 51 pm" src="https://cloud.githubusercontent.com/assets/6374832/19260391/f83efa50-8f3d-11e6-9848-0090016d03b6.png">

Any ideas?

**Comment by mrapogee** [comment]
This is actually a problem with the the Babylon complier. I forked this repo from the babel master in an attempt to play around with it. Babel won't compile this, even with the syntax plugin, because the parser is not pluggable and it has yet to implement the pipeline operator.

**Comment by amilajack** [comment]
So then I'm assuming that the babel parser was built to support jsx? I always thought it didn't work out of the box because we need to install babel-preset-react

**Comment by mrapogee** [comment]
@amilajack Yup, all a `babel-syntax-plugin` does is doe something like `parserOpts.plugins.push("jsx");` to enable a syntax feature.
